export const TOURNAMENTS = [
  { year:2026, host:"Canada, Mexico, United States", teams:48, champion:"Spain", runnerUp:"Argentina", scorer:"Kylian Mbappé", scorerGoals:10, attendance:6810966, matches:104 },
  { year:2022, host:"Qatar", teams:32, champion:"Argentina", runnerUp:"France", scorer:"Kylian Mbappé", scorerGoals:8, attendance:3404252, matches:64 },
  { year:2018, host:"Russia", teams:32, champion:"France", runnerUp:"Croatia", scorer:"Harry Kane", scorerGoals:6, attendance:3031768, matches:64 },
  { year:2014, host:"Brazil", teams:32, champion:"Germany", runnerUp:"Argentina", scorer:"James Rodríguez", scorerGoals:6, attendance:3429873, matches:64 },
  { year:2010, host:"South Africa", teams:32, champion:"Spain", runnerUp:"Netherlands", scorer:"Thomas Müller & others", scorerGoals:5, attendance:3178856, matches:64 },
  { year:2006, host:"Germany", teams:32, champion:"Italy", runnerUp:"France", scorer:"Miroslav Klose", scorerGoals:5, attendance:3352605, matches:64 },
  { year:2002, host:"Korea Republic, Japan", teams:32, champion:"Brazil", runnerUp:"Germany", scorer:"Ronaldo", scorerGoals:8, attendance:2705197, matches:64 },
  { year:1998, host:"France", teams:32, champion:"France", runnerUp:"Brazil", scorer:"Davor Šuker", scorerGoals:6, attendance:2785100, matches:64 },
  { year:1994, host:"United States", teams:24, champion:"Brazil", runnerUp:"Italy", scorer:"Hristo Stoichkov & Oleg Salenko", scorerGoals:6, attendance:3587538, matches:52 },
  { year:1990, host:"Italy", teams:24, champion:"Germany", runnerUp:"Argentina", scorer:"Salvatore Schillaci", scorerGoals:6, attendance:2516215, matches:52 },
  { year:1986, host:"Mexico", teams:24, champion:"Argentina", runnerUp:"West Germany", scorer:"Gary Lineker", scorerGoals:6, attendance:2394031, matches:52 },
  { year:1982, host:"Spain", teams:24, champion:"Italy", runnerUp:"West Germany", scorer:"Paolo Rossi", scorerGoals:6, attendance:2109723, matches:52 },
  { year:1978, host:"Argentina", teams:16, champion:"Argentina", runnerUp:"Netherlands", scorer:"Mario Kempes", scorerGoals:6, attendance:1545791, matches:38 },
  { year:1974, host:"West Germany", teams:16, champion:"West Germany", runnerUp:"Netherlands", scorer:"Grzegorz Lato", scorerGoals:7, attendance:1774022, matches:38 },
  { year:1970, host:"Mexico", teams:16, champion:"Brazil", runnerUp:"Italy", scorer:"Gerd Müller", scorerGoals:10, attendance:1673975, matches:32 },
  { year:1966, host:"England", teams:16, champion:"England", runnerUp:"West Germany", scorer:"Eusébio", scorerGoals:9, attendance:1563135, matches:32 },
  { year:1962, host:"Chile", teams:16, champion:"Brazil", runnerUp:"Czechoslovakia", scorer:"Multiple players (4 goals)", scorerGoals:4, attendance:893172, matches:32 },
  { year:1958, host:"Sweden", teams:16, champion:"Brazil", runnerUp:"Sweden", scorer:"Just Fontaine", scorerGoals:13, attendance:868000, matches:35 },
  { year:1954, host:"Switzerland", teams:16, champion:"West Germany", runnerUp:"Hungary", scorer:"Sándor Kocsis", scorerGoals:11, attendance:943000, matches:26 },
  { year:1950, host:"Brazil", teams:13, champion:"Uruguay", runnerUp:"Brazil", scorer:"Ademir", scorerGoals:9, attendance:1045246, matches:22 },
  { year:1938, host:"France", teams:15, champion:"Italy", runnerUp:"Hungary", scorer:"Leônidas", scorerGoals:7, attendance:375700, matches:18 },
  { year:1934, host:"Italy", teams:16, champion:"Italy", runnerUp:"Czechoslovakia", scorer:"Oldřich Nejedlý", scorerGoals:5, attendance:363000, matches:17 },
  { year:1930, host:"Uruguay", teams:13, champion:"Uruguay", runnerUp:"Argentina", scorer:"Guillermo Stábile", scorerGoals:8, attendance:590549, matches:18 },
];
export const TEAM_APPEARANCES = [
  { nation: "Brazil", apps: 22 },
  { nation: "Germany", apps: 20 },
  { nation: "Argentina", apps: 18 },
  { nation: "Italy", apps: 18 },
  { nation: "Mexico", apps: 17 },
  { nation: "England", apps: 16 },
  { nation: "France", apps: 16 },
  { nation: "Spain", apps: 16 },
  { nation: "Uruguay", apps: 14 },
  { nation: "Belgium", apps: 14 },
  { nation: "Serbia", apps: 13 },
  { nation: "Switzerland", apps: 12 },
  { nation: "Sweden", apps: 12 },
  { nation: "United States", apps: 11 },
  { nation: "Russia", apps: 11 },
  { nation: "Netherlands", apps: 11 },
  { nation: "Korea Republic", apps: 11 },
  { nation: "Hungary", apps: 9 },
  { nation: "Chile", apps: 9 },
  { nation: "Poland", apps: 9 },
  { nation: "Czech Republic", apps: 9 },
  { nation: "Paraguay", apps: 8 },
  { nation: "Portugal", apps: 8 },
  { nation: "Cameroon", apps: 8 },
  { nation: "Scotland", apps: 8 },
];